### ISSUE TITLE
Issue during First Time Use

### ISSUE THREAD

**Issue by nhalstead** [EsotericSoftware/powermate#1]
```
C:\Users\nhalstead\Desktop\powermate-1.02>java -jar powermate.jar debug
Searching...
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\nhalstead\Desktop\powermate-1.02\LibusbJava.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at ch.ntb.usb.LibusbJava.<clinit>(LibusbJava.java:364)
        at ch.ntb.usb.USB.init(USB.java:315)
        at ch.ntb.usb.USB.getBus(USB.java:296)
        at ch.ntb.usb.Device.initDevice(Device.java:102)
        at ch.ntb.usb.Device.open(Device.java:222)
        at powermate.PowerMate.run(PowerMate.java:50)
        at powermate.VolumeControl.<init>(VolumeControl.java:33)
        at powermate.VolumeControl.main(VolumeControl.java:69)

C:\Users\nhalstead\Desktop\powermate-1.02>
```

Not sure where to get the dependencies from and to see what I have done wrong.

**Comment by nhalstead** [comment]
Really Looking forward to using this software, the default/stock software **SUCKS**!

**Comment by NathanSweet** [comment]
You need the libusb-win32 driver, see here:
https://github.com/EsotericSoftware/powermate#installation

I eventually gave up on the PowerMate and got a Zoom UAC-2 just to use for volume control.

**Comment by iTrooper5118** [comment]
While I understand you've moved away a long time ago, some of us would love to get our dusty old Griffin knobs out of a box from the shed and try to get it working again.

I can see the volume is working, but is it just volume up and down that works? pressing the button does nothing, aka no muting or anything, and the light has never changed at any point.

I believe mine is one of the first gen knobs so I don't know if that is the issue?

My HID_VENDORID is 077D
HID_PRODUCTID is 0410
ID_VERSIONNUMBER is 0109

Not sure if any of that helps.

**Comment by TekSoup** [comment]
> While I understand you've moved away a long time ago, some of us would love to get our dusty old Griffin knobs out of a box from the shed and try to get it working again.
> 
> I can see the volume is working, but is it just volume up and down that works? pressing the button does nothing, aka no muting or anything, and the light has never changed at any point.
> 
> I believe mine is one of the first gen knobs so I don't know if that is the issue?
> 
> My HID_VENDORID is 077D HID_PRODUCTID is 0410 ID_VERSIONNUMBER is 0109
> 
> Not sure if any of that helps.

I was just thinking of mine a couple days ago, its here. :-)

**Comment by NathanSweet** [comment]
This function is called when the button is pressed, but doesn't do anything:
https://github.com/EsotericSoftware/powermate/blob/master/src/powermate/VolumeControl.java#L61
You'd need to modify the code to implement mute/whatever.

**Comment by iTrooper5118** [comment]
Does the nircmdc.exe do all the volume control? If so, is it programmed to fire off a mute command to the system? If yes, cool, it's a minor tweak to get that working. Although I know nothing about programming, but I do understand what the code is trying to say.

As I mentioned earlier, sadly the light dimming or getting bright when the knob is turned does nothing sadly. It's just stuck at one level of brightness, my assumption is cuz it's an earlier first gen (at least from 2003) it's slightly programmed different than later models. Despite all that, it surprisingly still works after 20 years.

At this time, without installing the libusb driver, just plugging it in, plain Jane, nothing but Windows 10 discovering the USB knob.  The knob acts like a mouse and moves the mouse pointer from left to right and pushing the button fires off a left click command.
